### ISSUE TITLE
infinite images? lazy loading?

### ISSUE THREAD

**Issue by jtkeyva** [MasahideMori-SimpleAppli/sakura_blizzard#2]
is it possible to have infinite images lazy loading? can they be webp or gif?

**Comment by MasahideMori-SimpleAppli** [comment]
Hi @jtkeyva ,

Thank you for opening this issue.

For lazy loading, I think it's a good idea to display the indicator as in the example.

I haven't tried WebP and GIF so I don't know, but I recommend PNG. PNG will probably work on any device.
Furthermore, when falling images, I think it will be difficult to use formats other than those that support transparent parts.

Thank you.

**Comment by jtkeyva** [comment]
Thank you. Still not sure if it can support lazy loading. What do you mean it's a good idea to display the indicator? WebP and GIF will allow for animations. I see that it works, but they are not animating. Any chance you can enable it to animate?

Thanks

**Comment by MasahideMori-SimpleAppli** [comment]
My comment "For lazy loading, I think it's a good idea to display the indicator as in the example." nuance is to create a StatefulWidget (child view is ImageFallView) that performs lazy loading, and display the CircularProgressIndicator while the image is loading. 
This package has nothing to do with the lazy loading process itself, so you will need to implement something that suits your use case.

I don't think it will work for animations set on the image file side. This package uses Flutter's custom painter to render, so it has different limitations than regular widgets.

In your case, instead of using this package, you may want to explore ways to animate the translation and rotation of the basic Widget.

If you cannot achieve what you want with the Widget's movement and rotation animations, you may be able to achieve it by modifying ElementsFlowView in this package. However, it's a bit complicated, so you might want to consider it if the common methods don't work.

Thank you.

**Comment by jtkeyva** [comment]
Got it thank you for your consideration. An infinite list of falling content would be really cool but sounds too difficult to achieve. I was thinking this may be a great start, but my knowledge is limited
